#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_END };

enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };

enum BOOLID	{ BOOL_TILE, BOOL_TREE, BOOL_END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER,  MAXCHANNEL };